### ISSUE TITLE
Wrong indication color for guess

### ISSUE THREAD

**Issue by pravinbanjade** [ashish336b/wordle-cli#6]
![Screenshot from 2022-03-14 10-18-43](https://user-images.githubusercontent.com/32491320/158105470-22930e17-8ec1-4908-b791-9af59fcd5af0.png)

Serous Bug on wrong color indication. Please see my first guess. "STALL" it show there are 2 L whereas the correct answer is "SMELT" with only 1 L

**Comment by ashish336b** [comment]
This is old version of the game. uninstall game using command ```sudo apt-get remove wordle``` and download latest release from link given in readme.md

**Comment by pravinbanjade** [comment]
Thank you. I guess I installed the old version again. Now working great
![Screenshot from 2022-03-14 10-55-55](https://user-images.githubusercontent.com/32491320/158108753-1f2266ff-b0e8-4c62-aee9-407e2155ba5f.png)
